"""
This is a setup.py script generated by py2applet and then edited

Usage:
    python3.5 setup.py py2app
"""

from setuptools import setup

APP = ['app/main_controller.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    name='GradeConverter',
    setup_requires=['py2app'], install_requires=['xlsxwriter'],
    tests_require=['pytest']
)
